"""Geometry optimization helpers."""

import os

from rdkit import Chem
from rdkit.Chem import AllChem


def optimize_with_rdkit(smiles, method="mmff"):
    """
    Generate and optimize 3D coordinates from SMILES using RDKit.

    Args:
        smiles (str): SMILES string of the molecule
        method (str): Force field method - 'mmff' or 'uff'. Defaults to 'mmff'.

    Returns:
        rdkit.Chem.Mol: RDKit molecule object with optimized 3D coordinates

    Raises:
        ValueError: If SMILES parsing fails or embedding fails
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Failed to parse SMILES: {smiles}")

    mol = Chem.AddHs(mol)

    # Embed molecule (generate 3D coordinates)
    result = AllChem.EmbedMolecule(mol, randomSeed=42)
    if result == -1:
        raise ValueError(f"Failed to embed molecule from SMILES: {smiles}")

    # Optimize geometry
    if method.lower() == "mmff":
        AllChem.MMFFOptimizeMolecule(mol)
    elif method.lower() == "uff":
        AllChem.UFFOptimizeMolecule(mol)
    else:
        raise ValueError(f"Unknown RDKit optimization method: {method}. Use 'mmff' or 'uff'.")

    return mol


def rdkit_mol_to_xyz(mol, output_path, comment="Generated by emsuite"):
    """
    Write an RDKit molecule to an XYZ file.

    Args:
        mol (rdkit.Chem.Mol): RDKit molecule with 3D coordinates
        output_path (str): Path to save the XYZ file
        comment (str): Comment line for the XYZ file

    Returns:
        str: Path to the saved XYZ file
    """
    conf = mol.GetConformer()

    with open(output_path, "w") as f:
        f.write(f"{mol.GetNumAtoms()}\n")
        f.write(f"{comment}\n")
        for i, atom in enumerate(mol.GetAtoms()):
            pos = conf.GetAtomPosition(i)
            f.write(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}\n")

    return output_path


def optimize_with_pyscf(
    xyz_path, method="dft", basis_set="6-31G*", functional="b3lyp", solvent=None, charge=0, spin=0
):
    """
    Optimize molecular geometry using PySCF.

    Args:
        xyz_path (str): Path to input XYZ file
        method (str): Calculation method - 'dft' or 'hf'. Defaults to 'dft'.
        basis_set (str): Basis set. Defaults to '6-31G*'.
        functional (str): DFT functional (only for method='dft'). Defaults to 'b3lyp'.
        solvent (str or None): Solvent name for SMD solvation. Defaults to None.
        charge (int): Molecular charge. Defaults to 0.
        spin (int): Spin (2S notation). Defaults to 0.

    Returns:
        str: Path to the optimized XYZ file (named <input>_opt.xyz)
    """
    # Import here to avoid circular imports and keep surface module lightweight
    from emsuite import core

    output_path = core.optimize_molecule(
        xyz_filepath=xyz_path,
        basis_set=basis_set,
        method=method,
        functional=functional,
        original_charge=charge,
        charge_change=0,
        gpu=core.check_gpu_info() > 0,
        spin_guesses=[spin] if spin is not None else None,
        solvent=solvent,
    )

    return output_path


def smiles_to_xyz(
    smiles,
    output_path,
    optimize=True,
    optimize_method="mmff",
    method="dft",
    basis_set="6-31G*",
    functional="b3lyp",
    solvent=None,
    charge=0,
    spin=0,
):
    """
    Convert SMILES to XYZ file with optional geometry optimization.

    Args:
        smiles (str): SMILES string
        output_path (str): Path to save the XYZ file
        optimize (bool): Whether to optimize geometry. Defaults to True.
        optimize_method (str): 'mmff', 'uff', or 'pyscf'. Defaults to 'mmff'.
        method (str): QM method for pyscf optimization. Defaults to 'dft'.
        basis_set (str): Basis set for pyscf optimization. Defaults to '6-31G*'.
        functional (str): Functional for pyscf optimization. Defaults to 'b3lyp'.
        solvent (str or None): Solvent for pyscf optimization. Defaults to None.
        charge (int): Molecular charge. Defaults to 0.
        spin (int): Spin (2S notation). Defaults to 0.

    Returns:
        str: Path to the generated (and optionally optimized) XYZ file
    """
    if optimize_method.lower() in ["mmff", "uff"]:
        # Use RDKit for fast optimization
        mol = optimize_with_rdkit(smiles, method=optimize_method) if optimize else None

        if mol is None:
            # Just embed without optimization
            mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
            AllChem.EmbedMolecule(mol, randomSeed=42)

        rdkit_mol_to_xyz(mol, output_path, comment=smiles)
        return output_path

    elif optimize_method.lower() == "pyscf":
        # First get initial geometry from RDKit (no optimization)
        mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
        result = AllChem.EmbedMolecule(mol, randomSeed=42)
        if result == -1:
            raise ValueError(f"Failed to embed molecule from SMILES: {smiles}")

        # Save initial geometry
        temp_xyz = output_path.replace(".xyz", "_initial.xyz")
        rdkit_mol_to_xyz(mol, temp_xyz, comment=smiles)

        if optimize:
            # Optimize with PySCF
            optimized_path = optimize_with_pyscf(
                temp_xyz,
                method=method,
                basis_set=basis_set,
                functional=functional,
                solvent=solvent,
                charge=charge,
                spin=spin,
            )
            # Rename to desired output path
            if optimized_path != output_path:
                os.rename(optimized_path, output_path)
            # Clean up temp file
            if os.path.exists(temp_xyz):
                os.remove(temp_xyz)
        else:
            os.rename(temp_xyz, output_path)

        return output_path
    else:
        raise ValueError(
            f"Unknown optimization method: {optimize_method}. Use 'mmff', 'uff', or 'pyscf'."
        )


##############################################
